// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using adm_vendas_webmvc.Data;

namespace adm_vendas_webmvc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240104194941_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("adm_vendas_webmvc.Models.SalesRecordModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SellersId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellersId");

                    b.ToTable("SalesRecord");
                });

            modelBuilder.Entity("adm_vendas_webmvc.Models.SellerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentsId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentsId");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("vendas_web_mvc.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("adm_vendas_webmvc.Models.SalesRecordModel", b =>
                {
                    b.HasOne("adm_vendas_webmvc.Models.SellerModel", "Sellers")
                        .WithMany("Sales")
                        .HasForeignKey("SellersId");

                    b.Navigation("Sellers");
                });

            modelBuilder.Entity("adm_vendas_webmvc.Models.SellerModel", b =>
                {
                    b.HasOne("vendas_web_mvc.Models.DepartmentModel", "Departaments")
                        .WithMany("Selleres")
                        .HasForeignKey("DepartamentsId");

                    b.Navigation("Departaments");
                });

            modelBuilder.Entity("adm_vendas_webmvc.Models.SellerModel", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("vendas_web_mvc.Models.DepartmentModel", b =>
                {
                    b.Navigation("Selleres");
                });
#pragma warning restore 612, 618
        }
    }
}
